# Generated by Django 4.0.5 on 2023-12-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_alter_bookmark_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
